name: First workflow
on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Enter the docker tag version"
        required: true
        default: "v1.0.0"
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: build docker image
      run: docker build -t first:1 .