name: First workflow
on: 
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: build docker image
      run: docker build -t first:1 .